min_version = "2024.9.5"

[tools]
python = "3.12"
ruff = "latest"
pre-commit = "latest"
task = "latest"
yamlfmt = "latest"
sops = "latest"
age = "latest"
"pipx:yamllint" = "latest"
uv = "latest"
docker-compose = "latest"

[env]
_.file = ".env"

ENV = "dev"

PROJECT_NAME = "{{ config_root | basename }}"

[tasks.info]
description = "Project infos"
run = '''
echo "Project : $PROJECT_NAME"
echo "Virtuel environnment : $VIRTUAL_ENV"
'''
