model_list:
  - model_name: llama3.2
    litellm_params:
      model: ollama_chat/llama3.2
      api_base: http://ollama:11434
      num_ctx: 4096

  # - model_name: qwen
  #   litellm_params:
  #     model: ollama_chat/qwen3.5:2b
  #     api_base: http://ollama:11434
  #     num_ctx: 4096
  #     temperature: 1.0
  #     top_p: 0.95
  #     extra_body:
  #       top_k: 20
  #       presence_penalty: 1.5

  # texte only
  - model_name: qwen
    litellm_params:
      model: ollama_chat/qwen3:4b
      api_base: http://ollama:11434
      extra_body:
        num_ctx: 4096
        temperature: 0.6
        top_p: 0.9
        repeat_penalty: 1.1
        num_predict: 1024
    model_info:
      mode: chat
      input_cost_per_token: 0
      output_cost_per_token: 0
      supports_function_calling: false

  - model_name: embedding
    litellm_params:
      model: ollama/nomic-embed-text
      api_base: http://ollama:11434

general_settings:
  # disable_cache_on_db_queries: true
  store_model_in_db: false # change to true or fix : Invalid proxy server token passed ... not found in db
  custom_headers:
    forward_headers:
      - X-OpenWebUI-User-Name
      - X-OpenWebUI-User-Id
      - X-OpenWebUI-User-Email
      - X-OpenWebUI-User-Role
      - X-OpenWebUI-Chat-Id
      - X-OpenWebUI-Session
      - X-Session-Id
  user_header_mappings:
    - header_name: X-OpenWebUI-User-Id
      litellm_user_role: internal_user
    - header_name: X-OpenWebUI-User-Email
      litellm_user_role: customer
litellm_settings:
  fallbacks:
    - qwen: ["llama3.2"]
  default_fallbacks: ["llama3.2"]
  # cache: true # TODO configure REDIS
  # cache_params:
  #   type: redis
  #   host: redis
  #   port: 6379
  request_timeout: 600
  num_retries: 1
  # snum_workers: 16
  # stream: true
  drop_params: true
  # set_verbose: true
  callbacks:
    # - hooks.openwebui_user_map.proxy_handler_instance
    # - hooks.langfuse_chat_only.proxy_handler_instance
    - langfuse_otel
    - prometheus
  success_callback: ["langfuse_otel"]
  failure_callback: ["langfuse_otel"]
  turn_off_message_logging: false
  langfuse_default_tags:
    - openwebui
    - thiga-ai
    - local-ollama
    - qwen
    - rag
    - assistant-thiga-solution-architect
    - prompt-v1
  prometheus_initialize_budget_metrics: true
router_settings:
  routing_strategy: simple-shuffle
